---
title: 'PEC4: Clasificación de Splice Junctions'
author: "Marcos Zamora Amengual"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: 
      collapsed: true
      smooth_scroll: true
    number_sections: true
    theme: cerulean
    highlight: textmate
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, comment = NULL, cache = TRUE)

setwd('D:/Users/marcos.zamora/Documents/Machine Learning')
```

# Introducción

<p align="justify">Vamos a generar una serie de clasificadores para predecir los sitios de splicing en el genoma, utilizando distintos algoritmos de Machine Learning. Vamos a realizar la codificación de los algoritmos en R usando el paquete caret. La finalidad del análisis es analizar la potencia de los distintos clasificadores de Machine Learning y generar una guía práctica de los principales algoritmos de clasificación que existen dentro del ML. Los algoritmos que utilizaremos para estudiar las Splice Junctions serán:<p>

- k-Nearest Neighbours
- Naive Bayes
- Artificial Neural Network
- Support Vector Machine
- Árbol de Clasificación
- Random Forest


# Obtención de las Muestras de Train y Test

<p align="justify">Para comenzar el análisis, lo primero que debemos hacer es introducir nuestros datos en R y dividirlos en dos sets de datos, train y test, para poder implementar los distintos clasificadores utilizando los mismo parámetros de entrada y por lo tanto poderlos comparar entre sí<p>